export const playerData = [
   {
      firstName: 'Colin',
      lastName: 'Castleton',
      image: 'https://cdn.nba.com/headshots/nba/latest/260x190/1630658.png',
      url: 'http://au.global.nba.com/players/colin_castleton/',
      team: 'LAL',
      position: 'C',
      height: '2.08',
      weight: '113.4 kg',
      experience: 0,
      country: 'United States'
   },
   {
      firstName: 'Max',
      lastName: 'Christie',
      image: 'https://cdn.nba.com/headshots/nba/latest/260x190/1631108.png',
      url: 'http://au.global.nba.com/players/max_christie/',
      team: 'LAL',
      position: 'G',
      height: '1.96',
      weight: '86.2 kg',
      experience: 1,
      country: 'United States'
   },
   {
      firstName: 'Anthony',
      lastName: 'Davis',
      image: 'https://cdn.nba.com/headshots/nba/latest/260x190/203076.png',
      url: 'http://au.global.nba.com/players/anthony_davis/',
      team: 'LAL',
      position: 'F-C',
      height: '2.08',
      weight: '114.8 kg',
      experience: 11,
      country: 'United States'
   },
   {
      firstName: 'Spencer',
      lastName: 'Dinwiddie',
      image: 'https://cdn.nba.com/headshots/nba/latest/260x190/203915.png',
      url: 'http://au.global.nba.com/players/spencer_dinwiddie/',
      team: 'LAL',
      position: 'G',
      height: '1.96',
      weight: '97.5 kg',
      experience: 9,
      country: 'United States'
   },
   {
      firstName: 'Harry',
      lastName: 'Giles III',
      image: 'https://cdn.nba.com/headshots/nba/latest/260x190/1628385.png',
      url: 'http://au.global.nba.com/players/harry_giles/',
      team: 'LAL',
      position: 'F-C',
      height: '2.08',
      weight: '108.9 kg',
      experience: 3,
      country: 'United States'
   },
   {
      firstName: 'Rui',
      lastName: 'Hachimura',
      image: 'https://cdn.nba.com/headshots/nba/latest/260x190/1629060.png',
      url: 'http://au.global.nba.com/players/rui_hachimura/',
      team: 'LAL',
      position: 'F',
      height: '2.03',
      weight: '104.3 kg',
      experience: 4,
      country: 'Japan'
   },
   {
      firstName: 'Jaxson',
      lastName: 'Hayes',
      image: 'https://cdn.nba.com/headshots/nba/latest/260x190/1629637.png',
      url: 'http://au.global.nba.com/players/jaxson_hayes/',
      team: 'LAL',
      position: 'C-F',
      height: '2.13',
      weight: '99.8 kg',
      experience: 4,
      country: 'United States'
   },
   {
      firstName: 'Jalen',
      lastName: 'Hood-Schifino',
      image: 'https://cdn.nba.com/headshots/nba/latest/260x190/1641720.png',
      url: 'http://au.global.nba.com/players/jalen_hood-schifino/',
      team: 'LAL',
      position: 'G',
      height: '1.96',
      weight: '97.5 kg',
      experience: 0,
      country: 'United States'
   },
   {
      firstName: 'LeBron',
      lastName: 'James',
      image: 'https://cdn.nba.com/headshots/nba/latest/260x190/2544.png',
      url: 'http://au.global.nba.com/players/lebron_james/',
      team: 'LAL',
      position: 'F',
      height: '2.06',
      weight: '113.4 kg',
      experience: 20,
      country: 'United States'
   },
   {
      firstName: 'Maxwell',
      lastName: 'Lewis',
      image: 'https://cdn.nba.com/headshots/nba/latest/260x190/1641721.png',
      url: 'http://au.global.nba.com/players/maxwell_lewis/',
      team: 'LAL',
      position: 'F',
      height: '2.01',
      weight: '88.5 kg',
      experience: 0,
      country: 'United States'
   },
   {
      firstName: 'Skylar',
      lastName: 'Mays',
      image: 'https://cdn.nba.com/headshots/nba/latest/260x190/1630219.png',
      url: 'http://au.global.nba.com/players/skylar_mays/',
      team: 'LAL',
      position: 'G',
      height: '1.90',
      weight: '93.0 kg',
      experience: 3,
      country: 'United States'
   },
   {
      firstName: 'Taurean',
      lastName: 'Prince',
      image: 'https://cdn.nba.com/headshots/nba/latest/260x190/1627752.png',
      url: 'http://au.global.nba.com/players/taurean_prince/',
      team: 'LAL',
      position: 'F',
      height: '1.98',
      weight: '98.9 kg',
      experience: 7,
      country: 'United States'
   },
   {
      firstName: 'Austin',
      lastName: 'Reaves',
      image: 'https://cdn.nba.com/headshots/nba/latest/260x190/1630559.png',
      url: 'http://au.global.nba.com/players/austin_reaves/',
      team: 'LAL',
      position: 'G',
      height: '1.96',
      weight: '89.4 kg',
      experience: 2,
      country: 'United States'
   },
   {
      firstName: 'Cam',
      lastName: 'Reddish',
      image: 'https://cdn.nba.com/headshots/nba/latest/260x190/1629629.png',
      url: 'http://au.global.nba.com/players/cameron_reddish/',
      team: 'LAL',
      position: 'F',
      height: '2.01',
      weight: '97.5 kg',
      experience: 4,
      country: 'United States'
   },
   {
      firstName: 'Jared',
      lastName: 'Vanderbilt',
      image: 'https://cdn.nba.com/headshots/nba/latest/260x190/1629020.png',
      url: 'http://au.global.nba.com/players/jared_vanderbilt/',
      team: 'LAL',
      position: 'F',
      height: '2.06',
      weight: '97.5 kg',
      experience: 5,
      country: 'United States'
   },
   {
      firstName: "D'Angelo",
      lastName: 'Russell',
      image: 'https://cdn.nba.com/headshots/nba/latest/260x190/1626156.png',
      url: 'http://au.global.nba.com/players/dangelo_russell/',
      team: 'LAL',
      position: 'G',
      height: '1.93',
      weight: '88.5 kg',
      experience: 8,
      country: 'United States'
   }
]
